import PlantCard from 'components/PlantCard';
import type { NextPage } from 'next';
import Head from 'next/head';
import * as React from 'react';
import plantsJson from '__mocks__/plants.json';
import styles from '../styles/Home.module.css';

const plants: Plant[] = Object.values(plantsJson);

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <ul className='grid grid-cols-2'>
          {plants.map((plant) => (
            <li key={plant.id} className='p-4'>
              <PlantCard plant={plant} />
            </li>
          ))}
        </ul>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
